export default function Footer({ meta }) {
  return (
    <footer style={{
      borderTop: '1px solid var(--border-subtle)',
      padding: '32px',
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      flexWrap: 'wrap', gap: '12px',
    }}>
      <p style={{ fontSize: '13px', color: 'var(--text-muted)' }}>
        Generated by{' '}
        <span style={{ fontWeight: 600, color: 'var(--text-secondary)' }}>RepoDocGen</span>
        {' · '}Powered by Gemini AI
      </p>

      <p style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
        {meta?.generatedAt && `Generated on ${new Date(meta.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`}
      </p>
    </footer>
  );
}
